{
 "title": "Layer 0 - Metal Blochchain",
 "description": "Home dashboard with the most important infrastructure indicators for your node and docker machine.",
 "tags": [ "MΞTA" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{job=\"node-exporter\"},instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Load",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{instance=\"$node\",job=\"$job\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{instance=\"$node\",job=\"$job\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Queries success",
   "type": "bargauge",
   "description": "Percentage of successful queries per chain in the last minute",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(metal_X_handler_chits_count{job=\"metalgo\"}[1m]) + 1) / (increase(metal_X_handler_chits_count{job=\"metalgo\"}[1m]) + increase(metal_X_handler_query_failed_count{job=\"metalgo\"}[1m]) + 1)",
     "legendFormat": "X Chain"
    },
    {
     "expr": "(increase(metal_P_handler_chits_count{job=\"metalgo\"}[1m]) + 1) / (increase(metal_P_handler_chits_count{job=\"metalgo\"}[1m]) + increase(metal_P_handler_query_failed_count{job=\"metalgo\"}[1m]) + 1)",
     "legendFormat": "P Chain"
    },
    {
     "expr": "(increase(metal_C_handler_chits_count{job=\"metalgo\"}[1m]) + 1) / (increase(metal_C_handler_chits_count{job=\"metalgo\"}[1m]) + increase(metal_C_handler_query_failed_count{job=\"metalgo\"}[1m]) + 1)",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Benched nodes",
   "type": "bargauge",
   "description": "Number of peers currently being benched (ignored) by the node",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metal_X_benchlist_benched_num{job=\"metalgo\"}",
     "legendFormat": "X Chain"
    },
    {
     "expr": "metal_P_benchlist_benched_num{job=\"metalgo\"}",
     "legendFormat": "P Chain"
    },
    {
     "expr": "metal_C_benchlist_benched_num{job=\"metalgo\"}",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Processing",
   "type": "bargauge",
   "description": "Number of blocks/vertices currently being processed by the node",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metal_X_vtx_processing{job=\"metalgo\"}",
     "legendFormat": "X Chain"
    },
    {
     "expr": "metal_P_blks_processing{job=\"metalgo\"}",
     "legendFormat": "P Chain"
    },
    {
     "expr": "metal_C_blks_processing{job=\"metalgo\"}",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Accepted Blocks/Vertices",
   "type": "bargauge",
   "description": "Number of blocks/vertices accepted in the last minute",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(metal_X_vtx_accepted_count{job=\"metalgo\"}[1m]))",
     "legendFormat": "X Chain"
    },
    {
     "expr": "round(increase(metal_P_blks_accepted_count{job=\"metalgo\"}[1m]))",
     "legendFormat": "P Chain"
    },
    {
     "expr": "round(increase(metal_C_blks_accepted_count{job=\"metalgo\"}[1m]))",
     "legendFormat": "C Chain"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "stat",
   "description": "Average time to get a response from a peer",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metal_requests_average_latency" }
   ]
  },
  {
   "title": "Proposed C blocks",
   "type": "stat",
   "description": "Number of blocks this node has proposed on the C-Chain in the last day. Since C-Chain blocks are produced at a fast rate, block producers are selected by stake weight.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(metal_C_blks_built{job=\"metalgo\"}[1d]))",
     "legendFormat": "Built C blocks"
    }
   ]
  },
  {
   "title": "Proposed P blocks",
   "type": "stat",
   "description": "Number of P-Chain blocks this node has proposed on the network in the last day. Since block production on P-Chain is usually below the target rate, every node proposes P blocks.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(metal_P_blks_built{job=\"metalgo\"}[1d]))",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "stat",
   "description": "Number of peers node is connected to",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metal_network_peers{job=\"metalgo\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "piechart",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}) ",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Operations Latency",
   "type": "timeseries",
   "description": "How long each database operation is taking on average",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(metal_db_put_sum{job=\"metalgo\"}[5m])/increase(metal_db_put_count{job=\"metalgo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(metal_db_get_sum{job=\"metalgo\"}[5m])/increase(metal_db_get_count{job=\"metalgo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(metal_db_delete_sum{job=\"metalgo\"}[5m])/increase(metal_db_delete_count{job=\"metalgo\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(metal_db_has_sum{job=\"metalgo\"}[5m])/increase(metal_db_has_count{job=\"metalgo\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(metal_db_compact_size_sum{job=\"metalgo\"}[5m])/increase(metal_db_compact_size_count{job=\"metalgo\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(metal_db_batch_put_sum{job=\"metalgo\"}[5m])/increase(metal_db_batch_put_count{job=\"metalgo\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(metal_db_batch_delete_sum{job=\"metalgo\"}[5m])/increase(metal_db_batch_delete_count{job=\"metalgo\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(metal_db_batch_reset_sum{job=\"metalgo\"}[5m])/increase(metal_db_batch_reset_count{job=\"metalgo\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(metal_db_batch_replay_sum{job=\"metalgo\"}[5m])/increase(metal_db_batch_replay_count{job=\"metalgo\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "Failing health checks",
   "type": "stat",
   "description": "Number of currently failing internal health checks",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metal_health_checks_failing{job=\"metalgo\"}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "C Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the C chain in the last minute.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(metal_C_blks_accepted_count{job=\"metalgo\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(metal_C_blks_rejected_count{job=\"metalgo\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Total staked",
   "type": "stat",
   "description": "Amount of METAL currently staked",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metal_P_vm_total_staked{job=\"metalgo\"}/1000000000",
     "legendFormat": "METAL"
    }
   ]
  },
  {
   "title": "Rewarding stake",
   "type": "stat",
   "description": "Percentage of the stake that view your node as sufficiently online and correct to vote that node be awarded at the end of the staking period.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metal_network_node_uptime_rewarding_stake{job=\"metalgo\"}",
     "legendFormat": "Rewarding stake"
    }
   ]
  },
  {
   "title": "P Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the P chain in the last minute.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(metal_P_blks_accepted_count{job=\"metalgo\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(metal_P_blks_rejected_count{job=\"metalgo\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "X Chain Vertices",
   "type": "timeseries",
   "description": "Number of accepted and rejected vertices on the X chain in the last minute",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(metal_X_vtx_accepted_count{job=\"metalgo\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(metal_X_vtx_rejected_count{job=\"metalgo\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  }
 ]
}