{
 "title": "Prometheus / Stats",
 "description": "Prometheus Stats Dashboard",
 "tags": [ "MΞTA" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(prometheus_build_info, job)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(prometheus_build_info, pod)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Build Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (namespace, instance, pod, version) (prometheus_build_info{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "max by (namespace, instance,pod) (process_start_time_seconds{job=~\"$job\"}*1000)\n"
    }
   ]
  },
  {
   "title": "Discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Targets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{job=~\"$job\",pod=~\"$pod\"})",
     "legendFormat": "Targets"
    }
   ]
  },
  {
   "title": "Target Sync [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$job\",pod=~\"$pod\"}[$interval])) by (scrape_job) * 1e3",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{job=~\"$job\",pod=~\"$pod\"})",
     "legendFormat": "Targets"
    }
   ]
  },
  {
   "title": "Retrieval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Scrape Interval Duration [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_sum{job=~\"$job\",pod=~\"$pod\"}[$interval]) / rate(prometheus_target_interval_length_seconds_count{job=~\"$job\",pod=~\"$pod\"}[$interval]) * 1e3",
     "legendFormat": "{{interval}} configured"
    }
   ]
  },
  {
   "title": "Scrape failures [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_exceeded_sample_limit_total[$interval]))",
     "legendFormat": "exceeded sample limit: {{job}}"
    },
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_duplicate_timestamp_total[$interval]))",
     "legendFormat": "duplicate timestamp: {{job}}"
    },
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_out_of_bounds_total[$interval]))",
     "legendFormat": "out of bounds: {{job}}"
    },
    {
     "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_out_of_order_total[$interval]))",
     "legendFormat": "out of order: {{job}}"
    }
   ]
  },
  {
   "title": "Appended Samples [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\",pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{job}} {{pod}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Head Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=~\"$job\",pod=~\"$pod\"}",
     "legendFormat": "{{job}} {{pod}} head series"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=~\"$job\",pod=~\"$pod\"}",
     "legendFormat": "{{job}} {{pod}} head chunks"
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_count{job=~\"$job\",pod=~\"$pod\",slice=\"inner_eval\"}[5m])",
     "legendFormat": "{{job}} {{pod}}"
    }
   ]
  },
  {
   "title": "Stage Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max by (slice) (prometheus_engine_query_duration_seconds{quantile=\"0.9\",job=~\"$job\",pod=~\"$pod\"}) * 1e3",
     "legendFormat": "{{slice}}"
    }
   ]
  }
 ]
}